### ISSUE TITLE
Comment issue

### ISSUE THREAD

**Issue by flexoron** [didoudiaz/gprolog#11]
$ ./src/TopComp/gprolog
GNU Prolog 1.5.0 (64 bits)
Compiled Sep 16 2021, 17:45:37 with gcc
Copyright (C) 1999-2021 Daniel Diaz

| ?- length(L,2).

L = [\_,\_]

yes
| ?- length(L,2). % comment

L = [\_,\_]

yes
| ?- length(L,N). % comment

L = []
N = 0 ? 
Action (; for next solution, a for all solutions, RET to stop) ?;

L = [\_]
N = 1 ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
Action (; for next solution, a for all solutions, RET to stop) ? 

yes
| ?-

**Comment by flexoron** [comment]
Can you explain what the difference here is?

Please try: Comment first  "% b", next  "% a"

$  ./src/TopComp/gprolog
GNU Prolog 1.5.0 (64 bits)
Compiled Sep 16 2021, 17:45:37 with gcc
Copyright (C) 1999-2021 Daniel Diaz

| ? length(L,N). % b

L = []
N = 0 ? 
Action (; for next solution, a for all solutions, RET to stop) ? 
:
yes
| ?-

| ?- length(L,N). % a
....output....
^C
Prolog interruption (h for help) ?

**Comment by didoudiaz** [comment]
The problem comes from the fact the behavior of the top-level which is a read-eval-write loop. In the read phase it reads a Prolog term (thus a term ended by a dot). The goal is then executed (eval) and the result is displayed (write). Due to backtracking several solutions can exist and the user is asked (to continue or not). Here the expected answer is just a character (not a Prolog term). Thus remaining characters in the keyboard buffer are thus read (and %... is no treated as a comment but interpreted by the top-level as a command).
