### ISSUE TITLE
format/2-3 predicates don't support using a list of characters for the format string

### ISSUE THREAD

**Issue by pmoura** [didoudiaz/gprolog#14]
The built-in `format/2-3` predicates support using either an atom or a list of character codes for the format string (as de facto standard) but not using a list of characters. A main advantage of adding support for also writing format strings using a list of characters is that, if we use double-quoted terms for the format strings in calls to the `format/2-3` predicates, the code will work independently of the current (standard) value of the `double_quotes` flag.

P.S. Prolog systems supporting atoms, chars, and codes for the format string include ECLiPSe, LVM, Scryer Prolog, SICStus Prolog, SWI-Prolog, and YAP.

**Comment by triska** [comment]
I would like to strongly support this, and I also have a minor qualification: In Scryer Prolog, I have made the conscious decision to support in fact *only* lists of characters as arguments in all `format`-style predicates. This includes the *nonterminal* `format_//2` that is used to describe formatted output *as a list of characters*, so that the entire output can be described as a list of characters, and thus become amenable to testing and reasoning. Hence, `format`-style predicates in Scryer&nbsp;Prolog uniformly use lists of characters for input and output. For example, we have:

<pre>
<b>?- phrase(format_("Hello, ~s!", ["world"]), Cs).</b>
   Cs = "Hello, world!".
</pre>

I have found working with lists of characters very convenient, much more convenient than codes when describing strings, and it would be great if GNU Prolog supports them too as format strings in `format/[2,3]`!

**Comment by pmoura** [comment]
With b34288b2f665918c4df8ffd8977ad7ea61241178:

```text
| ?- set_prolog_flag(double_quotes, chars).

yes
| ?- format("Hello ~w!", [world]).        
Hello world!

yes
| ?- set_prolog_flag(double_quotes, codes).       

yes
| ?- format("Hello ~w!", [world]).        
Hello world!

yes
| ?- set_prolog_flag(double_quotes, atom). 

yes
| ?- format("Hello ~w!", [world]).       
Hello world!

yes
```

Nice work!
