### ISSUE TITLE
How "to call expand_term/2 explicitly" (per manual 8.17.2)

### ISSUE THREAD

**Issue by dcnorris** [didoudiaz/gprolog#31]
With [this fork](https://github.com/dcnorris/wordnet-prolog), I am adapting wordnet-prolog for better ISO conformance. As detailed [here](https://github.com/dcnorris/wordnet-prolog/blob/master/gprolog.pl) gprolog runs the `[wn_valid]` check on the database, but slowly.

A technique based on `term_expansion/2`, [suggested](https://github.com/mthom/scryer-prolog/issues/1681#issuecomment-1374853910) by Markus Triska, helped Scryer Prolog to better index a crucial predicate, to overcome a similar run-time and perform on par with SWI on this goal. Is there example code I might follow, to see how "to call `expand_term/2` explicitly" in order to achieve the same success with gprolog?

**Comment by pmoura** [comment]
Logtalk's term-expansion mechanism answers one of the main points raised by Daniel:

> (...) executed in the same current environment (ie. knowing all user-defined predicates) which asserts clauses as soon as read and compiled.

The idea that the results of term-expansion are immediately available for use in compiling following clauses in the same source file is problematic as it makes predicates order in a file significant **and** restricts Prolog systems implementations to interpret source files as script-like. Moreover, mixing term-expansion rules with the terms to be expanded in the same source file makes reuse and combining expansions (in expansion workflows; see e.g. https://logtalk.org/manuals/libraries/hook_flows.html) more difficult and less transparent. These and other issues are discussed at:

- https://logtalk.org/manuals/userman/expansion.html
- https://logtalk.org/blog.html?tag=term-expansion

But back to the specific problem at hand. The solution I suggested allows you to expand the files in the repo you forked and then commit the resulting files in your fork. This way, there will be no need to perform any term-expansion at runtime when loading the files. P.S. You cal also use Logtalk to solve other portability issues but let's not go out of the scope of this issue here.

**Comment by dcnorris** [comment]
Thank you, Paulo, for this further explanation.  I had been approaching this on the view that wordnet-prolog is a very 'vanilla' application of Prolog, and accordingly had hoped that I might find at least 1 other Prolog implementations besides Scryer to which it could be adapted readily, with minimal changes to the codebase — say, by loading an implementation-specific adapter file ('scryer.pl', 'gprolog.pl', etc.) first.  This way, wherever all the adapter files share the same code, I would have a rationale for pushing that change down to the originally forked code.  (For example, both [`scryer.pl`](https://github.com/dcnorris/wordnet-prolog/blob/master/scryer.pl) and [`gprolog.pl`](https://github.com/dcnorris/wordnet-prolog/blob/master/gprolog.pl) contain the same snippet:

```prolog
apply(P, L) :- G =.. [P|L], G.
```
This, it seems to me, would 'recommend' making this transformation in the original codebase.  And what I contributed back via PR would constitute an adaptation (again, of supposedly 'vanilla' code) to multiple engines and not merely to my favorite one. ;)

What I am understanding from this conversation is that my (traditional?) view of loading Prolog scripts, interacting at a toplevel, etc., is not universal — and maybe not even ideal.  FWIW, I have failed today with yet another Prolog engine and may well give up this attempt and just admit that all I've done is adapted wordnet-prolog to Scryer.

**Comment by pmoura** [comment]
At https://github.com/LogtalkDotOrg/wordnet I'm currently only providing pack manifest files for the public WordNet repos without any attempt to make their code more portable. As you're aware, the core files are portable (being mostly Prolog facts) and only some utilities predicates on top of them require porting/updating for broader compatibility across Prolog systems. Part of the problem is that what's a built-in predicate in a system (e.g. `format/2`) can be a library predicate in another system. This can be solved e.g. (for most but not all systems) using de facto standard conditional compilation directives and the `dialect` flag. There's also the alternative you mentioned of using different adapter files.

But back to the issue topic. Some Prolog systems (e.g. SWI-Prolog) view source files as script-like and compile them in one go while others use multiple pass compilation (e.g. Ciao). Daniel already described GNU Prolog approach. Logtalk is also multi-pass. Regarding the term-expansion mechanism itself, there's no standard for it (official or de facto) and there are significant differences between systems (when they actually provide some version of it; not all do). Logtalk provides the only available portable implementation.

**Comment by didoudiaz** [comment]
@dcnorris did you see [other solution (in scryer-prolog issue)](https://github.com/mthom/scryer-prolog/issues/1681#issuecomment-1602996049) ? As I said there, I had to modify some code of your fork (to be less SWI-dependent). I can share it with you if you are still interested in updating your fork (you can contact me by mail didou.diaz at gm...).
