### ISSUE TITLE
Optimized `call_nth/2`

### ISSUE THREAD

**Issue by notoria** [didoudiaz/gprolog#45]
The predicate `call_nth/2` could be optimized if hand-compiled:
```
$ cd /tmp/call_nth
$ cat call_nth.wam
% compiler: GNU Prolog 1.5.0
% file    : call_nth.pl


file_name('/tmp/call_nth.pl').


predicate('$call_nth'/2,1,static,private,monofile,global,[
    allocate(3),
    get_variable(y(0),1),
    % put_integer(1152921504606846974,1), % test overflow.
    put_integer(0,1),
    get_variable(y(1),1),

    put_atom(call_nth,1),
    put_integer(2,2),
    put_atom(true,3),
    call('$call'/4),

    % Fast.
    % math_load_value(y(1),0),
    % call_c('Pl_Fct_Inc',[fast_call,x(0)],[x(0)]),

    % Slow.
    put_value(y(1),0),
    put_variable(y(2),1),
    % call(succ/2),
    call_c('Pl_Set_Bip_Name_Untagged_2',[by_value],[call_nth,2]),
    call_c('Pl_Succ_2',[boolean],[x(0),x(1)]),
    put_value(y(2),0),

    get_variable(y(1),0),
    get_value(y(0),0),

    deallocate,
    proceed]).
$
```
Then to compiled it:
```
$ cd /tmp/call_nth
$ cat compile.sh
#!/bin/sh

# Source: http://www.gprolog.org/manual/html_node/gprolog009.html

PATH=$PATH:/tmp/gprolog/bin

# gplc -W call_nth.pl
gplc -M --comment call_nth.wam
gplc -S --comment call_nth.ma
gplc -c call_nth.s
gplc -o call_nth -s call_nth.o
$
```
And combined with:
```
$ cd /tmp/call_nth
$ cat call_nth.pl
'@call_nth'(G_0, N) :-
    var(N), !,
    '$call_nth'(G_0, N).
'@call_nth'(G_0, N) :-
    integer(N),
    N @>= 0, !,
    N @> 0,
    '$call_nth'(G_0, N), !.
'@call_nth'(_, N) :-
    integer(N),
    throw(error(domain_error(not_less_than_zero,N),'@call_nth'/2)).
'@call_nth'(_, N) :-
    throw(error(type_error(integer,N),'@call_nth'/2)).
$
```
Benchmark:
```
$ cd /tmp/call_nth
$ PATH=$PATH:/tmp/gprolog/bin ./call_nth
GNU Prolog 1.6.0 (64 bits)
Compiled Jun 27 2023, 16:35:39 with gcc
Copyright (C) 1999-2023 Daniel Diaz

| ?- [call_nth].
compiling /tmp/call_nth/call_nth.pl for byte code...
/tmp/call_nth/call_nth.pl compiled, 44 lines read - 1965 bytes written, 7 ms

yes
| ?- [user].
compiling user for byte code...
query(N) :-
    call_nth(repeat, N0),
    N0 = N, !.

'@query'(N) :-
    '@call_nth'(repeat, N0),
    N0 = N, !.

user compiled, 38 lines read - 799 bytes written, 2916 ms

yes
| ?- query(16777216).

(7217 ms) yes
| ?- '@query'(16777216).

(5837 ms) yes
| ?- call_nth(repeat, 16777216).

(3348 ms) yes
| ?- '@call_nth'(repeat, 16777216).

(1501 ms) yes
| ?-
```
GNU Prolog installation:
```
$ cd /tmp
$ git clone https://github.com/didoudiaz/gprolog
$ cd gprolog/src
$ clear; make distclean; ./configure --with-install-dir=in-place --with-c-flags=debug; make -j$(nproc); make install
```

For the user, are the WAM instructions unstable to hand-compile it? Is there an alternative way to compile the instructions without creating a new binary?

**Comment by UWN** [comment]
Does this version overflow checking? The `succ/2` version does so.

**Comment by notoria** [comment]
Yes, it uses `succ/2` with `call(succ/2)` or `call_c('Pl_Succ_2',[boolean],[x(0),x(1)])`. But the faster version with `math_load_value(y(1),0), call_c('Pl_Fct_Inc',[fast_call,x(0)],[x(0)])` doesn't do the checking

**Comment by UWN** [comment]
So this is an optimization waiting to fail.

**Comment by notoria** [comment]
There are two version, one that uses `succ/2` that's fast and an other that uses `call_c('Pl_Fct_Inc',[fast_call,x(0)],[x(0)])` that's even faster. The optimization for the version with `succ/2` is valid (safe).

**Comment by UWN** [comment]
Please no unsafe optimizations. One purpose of `call_nth/2` is to support testing. Roughly, `call_nth(Gen_0, Nth), call(Test_0)`. You can now easily trace "where you are" with `Nth` and then rerun things exactiter only from a certain number on. So you get a very similar memory layout. Or you want to parallelize the effort, so you say `call_nth(Gen_0, Nth), Nth mod Nodenumber =:= NodeId, call(Test_0)` on each node. In such a context unsafe optimizations are really the worst. In particular if things run for months...

**Comment by didoudiaz** [comment]
About the current `call_nth/2` implementations: I could implement it in C but I opted for a simple Prolog implementation. It uses a non-backtrackable `setarg` to manage the counter and increment it over backtracking. The proposed optimization consists in storing the counter in a permanent variable (WAM terminology). This is clever and more efficient. Thank you for the detailed solution.

Note however that the benefits of this optimization must be kept in perspective. Its real impact depends on the time required by the goal itself. In this case (a simple `repeat`), the overhead of `call_nth` is significant (as the time spent counting solutions with `setarg` is roughly similar to the time to execute the `repeat`). For a more costly goal, the gain will become less significant. Anyway, it is an interesting optimization.

Moreover, it relies on writing WAM code directly, which at present offers no guarantee over time, as the `.wam` file format is still evolving. But this could be considered in the near future (or even provide a mechanism for inlining WAM code directly into Prolog code).

I'll be thinking about a simple way to benefit from this optimization in the long term.

NB: you can simplify the compilation chain. You'll get an executable directly with one `gplc` command as follows:
```
gplc -o call_nth call_nth.wam
```
You can even combine it with your `call_nth.pl` (the one defining `@call_nth/2' and calling `$call_nth/2`)
```
gplc -o call_nth call_nth.wam call_nth.pl
```
NB: The names are a bit confusing since `call_nth.wam` seems to be a compiled version of `call_nth.pl`. Anyway this works since `gplc` uses temporary intermediate files. You can see them passing `-v` to `gplc`.

**Comment by UWN** [comment]
A small suggestion to make the current implementation marginally less efficient, but more robust in view of future optimizations, Just add a second argument to `'$call_nth_counter'/1` which will always be a variable, [like here](https://stackoverflow.com/a/11400256/772868). In this manner possible future optimizations as [Representation Sharing](https://arxiv.org/abs/1106.1311) will not harm this at all.

**Comment by didoudiaz** [comment]
@notoria I propose a new version which acts as your implementation in Prolog. It is based on a `$call_c` extension `ret(RetVar)` to store the return value in a _permanent variable_ (i.e. a WAM Y variable stored in the predicate environment). 
It preserves all error cases.
@UWN: thanks for the suggestion (no longer needed in the optimized version however but kept as comment).

**Comment by notoria** [comment]
This version uses three variables, `y(0)` for the argument to unify later, `y(1)` for the counter and `y(2)` as a temporary (to not allocate on the heap). Is that a new extension?

**Comment by didoudiaz** [comment]
I just pushed it.

**Comment by notoria** [comment]
Perfect, it works.
